export function getKeywords() {
  const guestWordGame = [
    'làm',
    'lấy',
    'thấy',
    'nghĩ',
    'cho',
    'nhìn',
    'dùng',
    'tìm kiếm',
    'mong muốn',
    'đặt xuống',
    'biến hóa',
    'rời khỏi',
    'làm việc',
    'cầm nắm',
    'cảm thấy',
    'hỏi',
    'trình diễn',
    'thử',
    'gọi',
    'giữ',
    'cung cấp',
    'xoay',
    'theo dõi',
    'bắt đầu',
    'đem lại',
    'đi nhanh',
    'giúp đỡ',
    'chạy',
    'viết',
    'di chuyển',
    'chơi',
    'trả',
    'nghe',
    'tin tưởng',
    'cho phép',
    'gặp gỡ',
    'dẫn dắt',
    'đứng',
    'mang vác',
    'nói chuyện',
    'xuất hiện',
    'sản xuất',
    'ngồi ',
    'yêu cầu',
    'cân nhắc',
    'chờ đợi',
    'đề nghị',
    'đọc',
    'tiếp tục',
    'thêm vào',
    'thay đổi',
    'ngã',
    'nhớ lại',
    'mua',
    'dừng lại',
    'gửi',
    'nhận',
    'quyết định',
    'chiến thắng',
    'hiểu',
    'miêu tả',
    'phát triển',
    'đồng ý',
    'mở',
    'xây dựng',
    'dành giật',
    'trở lại',
    'vẽ',
    'viết',
    'hy vọng',
    'sáng tạo',
    'đi bộ',
    'gây ra',
    'nấu ăn',
    'đánh nhau',
    'lăn lộn',
    'múa ba lê',
    'nhõng nhẽo',
    'khiêu vũ',
    'hát',
    'nhảy',
    'nhào lộn',
    'uống nước',
    'ăn tối',
    'quay tay',
    'gật đầu',
    'gãi mông',
    'tập thể dục',
    'vỗ tay',
    'hít đất',
    'thở',
    'cười',
    'suy nghĩ',
    'la/hét/gào thét',
    'chải tóc',
    'tắm',
    'thoa son',
    'vuốt tóc',
    'mặc áo',
    'cột dây giày',
    'khóc',
    'điện giật',
    'cầu hôn',
    'vật tay',
    'cử tạ',
    'đập tay',
    'chèo',
    'rùng mình',
    'lái xe',
    'đạp xe',
    'tức/giận',
    'buồn',
    'vui',
    'thư giãn',
    'thất vọng',
    'ngạc nhiên',
    'giật mình',
    'đau đớn',
    'mệt mỏi',
    'sợ hãi',
    'tự tin',
    'lạc lõng',
    'cô đơn',
    'nhức đầu',
    'đau lưng',
    'buồn ngủ',
    'đau bụng',
    'khó thở',
    'say/xỉn',
    'lạnh',
    'nóng',
    'bứt rứt',
    'ngứa ngáy',
    'no',
    'đói',
    'buồn nôn',
    'đau tim',
    'đau họng',
    'khát nước',
    'chán/nãn',
    'phê',
    'lo lắng',
    'nhớ',
    'hạnh phúc',
    'hãnh diện',
    'nằm',
    'chào',
    'ném',
    'gánh',
    'giặt',
    'rửa',
    'đạp',
    'sủa',
    'gáy',
    'chửi',
    'hôn',
    'lừa',
    'hóng',
    'ngủ',
    'nấu',
    'bán',
    'ngửi',
    'liếm',
    'sờ',
    'bóp',
    'nặn',
    'vặn',
    'yêu',
    'ghét',
    'căng thẳng',
    'tuyệt vọng',
  ]
  const olympiaGame = [
    'B: Hổ còn được gọi là ông gì',
    'B: lão hạc tự tử bằng cái gì',
    'B: Tên 1 trường đại học ở ĐN',
    'B: Tế bào máu có nhân màu trắng nhạt tên là gì',
    'B: Tên bộ phim hình sự nhiều tập nổi tiếng của Italy về thế giới mafia đã được chiếu ở VN',
    'B: Tên diễn viên vào vai nam chính trong phim Mùa Ổi có 3 chữ B',
    'B: Cầu thử christiano Ronaldo của đội MU mang quốc tịch gì',
    'B: Trong 1 ca khúc của nhạc sĩ Nguyễn Cường: “Ta yêu nhau từ đâu” ?',
    'B: Hồ 3 bể nằm ở tỉnh nào',
    'B: hình ảnh thu nhỏ và khái quát hoá 1 phần mặt đất lên mặt giấy phẳng gọi là gì',
    'B: người đỗ thứ 2 sau trạng nguyên gọi là gì',
    'B: 1 bài hát của nhạc sĩ nguyễn minh tiến tham gia chương trình bài Việt Nam 2006',
    'B: làng nghề gốm sứ nổi tiếng ở ngoại thành hà nội',
    'B: Trong truyện trạng quỳnh, trạng chết thì chúa làm sao ?',
    'B: loại hoa màu tím nở vào mùa hè, gắn liền với thời học sinh ',
    'B: Tên 1 bài thơ nổi tiếng và cũng là 1 tập thơ của nhà thơ Bằng Việt',
    'B: Loại chim tượng trưng cho hoà bình',
    'B: Tính từ chỉ sự chắc chắn và lâu hỏng',
    'B: Tên khác của bài hát Đàn Chim Việt do nhạc sĩ Văn Cao sáng tác',
    'CH: Người ta thường đồ xôi vào cái gì',
    'CH: người ta thường ăn bánh cuốn kèm theo 1 món gì',
    'CH: có câu thành ngữ: xẩy cha còn',
    'CH: Các cơn mưa giông thường kèm theo gì',
    'CH: đồng bào vùng dân tộc việt bắc thường mặc trang phục có màu gì',
    'CH: Trong các bữa tiệc sinh nhật chúng ta thường nói với chủ nhân bữa tiệc câu gì',
    'CH: Trong ca dao VN, còn gì khóc đứng khóc ngồi, mẹ ơi đi chợ mua tôi đồng giềng',
    'CH: Trong thời tiết hanh khô nắng nóng kéo dài, chúng ta hết sức đề phòng sự cố gì',
    'CH: Con gì bay thấp thì mưa bay cao thì nắm bay vừa thì râm',
    'CH: Hành động dơ 2 ngón tay hình chữ V biểu thị điều gì',
    'CH: Loại đồ chơi có nhiều cánh chạy bằng sức gió tên là gì',
    'CH: Khi đi bơi nếu không khởi động kĩ thì dễ bị hiện tượng gì',
    'CH: Có câu ca dao: "đồng đăng có phố kì lừa, có nàng tô thị, có ..." ',
    'CH: Trong tiếng miền nam, hành vi lấy đồ của người khác gọi là gì?',
    'CH: để làm chứng minh thư hay hộ chiếu chúng ta cần chụp ảnh gì?',
    'CH: nghề đánh cá được gọi là nghề gì?',
    'CH: tập 4 của truyện harry porter có tên là harry porter và ...?',
    'CH: Trong bài Tràng giang Huy Cận đã viết: nắng xuống trời lên sâu như thế nào ?',
    'CH: Liễu Thăng: tướng xâm lược của nhà Minh bị chém đầu ở ải nào?',
    'CH: Để chỉ những người keo kiệt có câu thành ngữ: vắt cổ gì ra nước ?',
    'CH: Vợ của anh mõ trong vở Quan âm thị kính mở đầu bài dao bằng câu gì?',
    'CH: Đồ dùng bằng sành sứ thường được các người dân tộc vùng tây nguyên dùng để đựng rượu bằng gì?',
  ]

  return olympiaGame;
}
