export function getKeywords() {
  const guestWordGame = [
    'làm',
    'lấy',
    'thấy',
    'nghĩ',
    'cho',
    'nhìn',
    'dùng',
    'tìm kiếm',
    'mong muốn',
    'đặt xuống',
    'biến hóa',
    'rời khỏi',
    'làm việc',
    'cầm nắm',
    'cảm thấy',
    'hỏi',
    'trình diễn',
    'thử',
    'gọi',
    'giữ',
    'cung cấp',
    'xoay',
    'theo dõi',
    'bắt đầu',
    'đem lại',
    'đi nhanh',
    'giúp đỡ',
    'chạy',
    'viết',
    'di chuyển',
    'chơi',
    'trả',
    'nghe',
    'tin tưởng',
    'cho phép',
    'gặp gỡ',
    'dẫn dắt',
    'đứng',
    'mang vác',
    'nói chuyện',
    'xuất hiện',
    'sản xuất',
    'ngồi ',
    'yêu cầu',
    'cân nhắc',
    'chờ đợi',
    'đề nghị',
    'đọc',
    'tiếp tục',
    'thêm vào',
    'thay đổi',
    'ngã',
    'nhớ lại',
    'mua',
    'dừng lại',
    'gửi',
    'nhận',
    'quyết định',
    'chiến thắng',
    'hiểu',
    'miêu tả',
    'phát triển',
    'đồng ý',
    'mở',
    'xây dựng',
    'dành giật',
    'trở lại',
    'vẽ',
    'viết',
    'hy vọng',
    'sáng tạo',
    'đi bộ',
    'gây ra',
    'nấu ăn',
    'đánh nhau',
    'lăn lộn',
    'múa ba lê',
    'nhõng nhẽo',
    'khiêu vũ',
    'hát',
    'nhảy',
    'nhào lộn',
    'uống nước',
    'ăn tối',
    'quay tay',
    'gật đầu',
    'gãi mông',
    'tập thể dục',
    'vỗ tay',
    'hít đất',
    'thở',
    'cười',
    'suy nghĩ',
    'la/hét/gào thét',
    'chải tóc',
    'tắm',
    'thoa son',
    'vuốt tóc',
    'mặc áo',
    'cột dây giày',
    'khóc',
    'điện giật',
    'cầu hôn',
    'vật tay',
    'cử tạ',
    'đập tay',
    'chèo',
    'rùng mình',
    'lái xe',
    'đạp xe',
    'tức/giận',
    'buồn',
    'vui',
    'thư giãn',
    'thất vọng',
    'ngạc nhiên',
    'giật mình',
    'đau đớn',
    'mệt mỏi',
    'sợ hãi',
    'tự tin',
    'lạc lõng',
    'cô đơn',
    'nhức đầu',
    'đau lưng',
    'buồn ngủ',
    'đau bụng',
    'khó thở',
    'say/xỉn',
    'lạnh',
    'nóng',
    'bứt rứt',
    'ngứa ngáy',
    'no',
    'đói',
    'buồn nôn',
    'đau tim',
    'đau họng',
    'khát nước',
    'chán/nãn',
    'phê',
    'lo lắng',
    'nhớ',
    'hạnh phúc',
    'hãnh diện',
    'nằm',
    'chào',
    'ném',
    'gánh',
    'giặt',
    'rửa',
    'đạp',
    'sủa',
    'gáy',
    'chửi',
    'hôn',
    'lừa',
    'hóng',
    'ngủ',
    'nấu',
    'bán',
    'ngửi',
    'liếm',
    'sờ',
    'bóp',
    'nặn',
    'vặn',
    'yêu',
    'ghét',
    'căng thẳng',
    'tuyệt vọng',
  ]
  const olympiaGame = [
    'hổ còn được gọi là ông gì',
    'lão hạc tự tử bằng cái gì',
    'Tên 1 trường đại học ở ĐN',
    'Tế bào máu có nhân màu trắng nhạt tên là gì',
    'Tên bộ phim hình sự nhiều tập nổi tiếng của Italy về thế giới mafia đã được chiếu ở VN',
    'Tên diễn viên vào vai nam chính trong phim Mùa Ổi có 3 chữ B',
    'Cầu thử christiano Ronaldo của đội MU mang quốc tịch gì',
    'Trong 1 ca khúc của nhạc sĩ Nguyễn Cường: “Ta yêu nhau từ đâu” ?',
    'Hồ 3 bể nằm ở tỉnh nào (bắc cạn)',
    'hình ảnh thu nhỏ và khái quát hoá 1 phần mặt đất lên mặt giấy phẳng gọi là gì',
    'người đỗ thứ 2 sau trạng nguyên gọi là gì',
    '1 bài hát của nhạc sĩ nguyễn minh tiến tham gia chương trình bài Việt Nam 2006',
    'làng nghề gốm sứ nổi tiếng ở ngoại thành hà nội',
    'Trong truyện trạng quỳnh, trạng chết thì chúa làm sao ?',
    'loại hoa màu tím nở vào mùa hè, gắn liền với thời học sinh ',
    'Tên 1 bài thơ nổi tiếng và cũng là 1 tập thơ của nhà thơ Bằng Việt',
    'Loại chim tượng trưng cho hoà bình',
    'Tính từ chỉ sự chắc chắn và lâu hỏng',
    'Tên khác của bài hát Đàn Chim Việt do nhạc sĩ Văn Cao sáng tác',
  ]
  
  return olympiaGame;
}
