export function getKeywords() {
  return [
    'làm',
    'lấy',
    'thấy',
    'nghĩ',
    'cho',
    'nhìn',
    'dùng',
    'tìm kiếm',
    'mong muốn',
    'đặt xuống',
    'biến hóa',
    'rời khỏi',
    'làm việc',
    'cầm nắm',
    'cảm thấy',
    'hỏi',
    'trình diễn',
    'thử',
    'gọi',
    'giữ',
    'cung cấp',
    'xoay',
    'theo dõi',
    'bắt đầu',
    'đem lại',
    'đi nhanh',
    'giúp đỡ',
    'chạy',
    'viết',
    'di chuyển',
    'chơi',
    'trả',
    'nghe',
    'tin tưởng',
    'cho phép',
    'gặp gỡ',
    'dẫn dắt',
    'đứng',
    'mang vác',
    'nói chuyện',
    'xuất hiện',
    'sản xuất',
    'ngồi ',
    'yêu cầu',
    'cân nhắc',
    'chờ đợi',
    'đề nghị',
    'đọc',
    'tiếp tục',
    'thêm vào',
    'thay đổi',
    'ngã',
    'nhớ lại',
    'mua',
    'dừng lại',
    'gửi',
    'nhận',
    'quyết định',
    'chiến thắng',
    'hiểu',
    'miêu tả',
    'phát triển',
    'đồng ý',
    'mở',
    'xây dựng',
    'dành giật',
    'trở lại',
    'vẽ',
    'viết',
    'hy vọng',
    'sáng tạo',
    'đi bộ',
    'gây ra',
    'nấu ăn',
    'đánh nhau',
    'lăn lộn',
    'múa ba lê',
    'nhõng nhẽo',
    'khiêu vũ',
    'hát',
    'nhảy',
    'nhào lộn',
    'uống nước',
    'ăn tối',
    'quay tay',
    'gật đầu',
    'gãi mông',
    'tập thể dục',
    'vỗ tay',
    'hít đất',
    'thở',
    'cười',
    'suy nghĩ',
    'la/hét/gào thét',
    'chải tóc',
    'tắm',
    'thoa son',
    'vuốt tóc',
    'mặc áo',
    'cột dây giày',
    'khóc',
    'điện giật',
    'cầu hôn',
    'vật tay',
    'cử tạ',
    'đập tay',
    'chèo',
    'rùng mình',
    'lái xe',
    'đạp xe',
    'tức/giận',
    'buồn',
    'vui',
    'thư giãn',
    'thất vọng',
    'ngạc nhiên',
    'giật mình',
    'đau đớn',
    'mệt mỏi',
    'sợ hãi',
    'tự tin',
    'lạc lõng',
    'cô đơn',
    'nhức đầu',
    'đau lưng',
    'buồn ngủ',
    'đau bụng',
    'khó thở',
    'say/xỉn',
    'lạnh',
    'nóng',
    'bứt rứt',
    'ngứa ngáy',
    'no',
    'đói',
    'buồn nôn',
    'đau tim',
    'đau họng',
    'khát nước',
    'chán/nãn',
    'phê',
    'lo lắng',
    'nhớ',
    'hạnh phúc',
    'hãnh diện',
    'nằm',
    'chào',
    'ném',
    'gánh',
    'giặt',
    'rửa',
    'đạp',
    'sủa',
    'gáy',
    'chửi',
    'hôn',
    'lừa',
    'hóng',
    'ngủ',
    'nấu',
    'bán',
    'ngửi',
    'liếm',
    'sờ',
    'bóp',
    'nặn',
    'vặn',
    'yêu',
    'ghét',
    'căng thẳng',
    'tuyệt vọng',
  ]
}
